package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u20/1074/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, July 30, 2014 1:14:28 PM PDT
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
     */
  public static final short value = (short)(2);
}
